name: Release

on:
  release:
    types:
      - created

jobs:
  export:    
    runs-on: windows-latest
    
    env:
      clangLayoutSolution: Parsers/ClangLayout/ClangLayout.sln
      pdbLayoutSolution: Parsers/PDBLayout/PDBLayout.sln
      extensionSolutionName: StructLayout/StructLayout.sln
      extensionDir: StructLayout
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout LLVM library
      uses: actions/checkout@v4
      with:
        repository: Viladoman/ClangArtifacts
        sparse-checkout: llvm-project
        path: External
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
       
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
       
    - name: Build Clang Layout
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 ${{ env.clangLayoutSolution }}
      
    - name: Build PDB Layout
      run: msbuild /m /p:Configuration=Release /p:Platform=x64 ${{ env.pdbLayoutSolution }}
      
    - name: NuGet restore Struct Layout
      run: nuget restore ${{ env.extensionSolutionName }}
     
    - name: Build Struct Layout VSIX
      run: msbuild /m /p:Configuration=Release ${{ env.extensionSolutionName }}
      
    - name: Upload VSIX 2019 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{env.extensionDir}}/VSIX16/bin/Release/StructLayout.vsix
        asset_name: StructLayout_VS2019.vsix
        asset_content_type: application/zip
    
    - name: Upload VSIX 2022 Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{env.extensionDir}}/VSIX17/bin/Release/StructLayout.vsix
        asset_name: StructLayout_VS2022.vsix
        asset_content_type: application/zip